name: benji_user
description: Benji user app.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  hexcolor: ^3.0.1
  cupertino_icons: ^1.0.6
  flutter_spinkit: ^5.2.0
  csc_picker: ^0.2.7
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.0
  geolocator: ^10.0.1
  permission_handler: ^11.0.0
  flutter_pw_validator: ^1.6.0
  intl_phone_field: ^3.2.0
  image_picker: ^1.0.4
  url_launcher: ^6.1.14
  liquid_pull_to_refresh: ^3.0.1
  shared_preferences: ^2.2.1
  font_awesome_flutter: ^10.5.0
  lottie: ^2.6.0
  get_it: ^7.6.4
  intl: ^0.18.1
  flutter_layout_grid: ^2.0.5
  dotted_border: ^2.0.0+3
  shimmer: ^3.0.0
  readmore: ^2.2.0
  flutter_svg: ^2.0.7
  flutter_dotenv: ^5.1.0
  flutter_carousel_widget: ^2.1.0
  flutter_polyline_points: ^2.0.0
  autoscale_tabbarview: ^1.0.2
  share_plus: ^7.1.0
  screenshot: ^2.1.0
  path_provider: ^2.1.1
  pdf: ^3.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2

flutter_native_splash:
  image: assets/images/splash_screen/frame_1.png
  color: "#f9f9f9"
  image_dark: assets/images/splash_screen/frame_1.png
  color_dark: "#000000"

flutter_launcher_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/images/logo/benji_blue_logo_icon.jpg"
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo/
    - assets/images/vendors/
    - assets/images/splash_screen/
    - assets/images/onboarding_screen/
    - assets/images/vendors/
    - assets/icons/
    - assets/images/rider/
    - assets/images/profile/
    - assets/images/products/
    - assets/images/customers/
    - assets/animations/login/
    - assets/animations/signup/
    - assets/animations/payment/
    - assets/animations/no_internet/
    - assets/animations/error/
    - assets/animations/empty/
    - assets/animations/credit_card/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
