name: benji_user
description: Benji user app.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  hexcolor:
  cupertino_icons:
  flutter_spinkit:
  csc_picker:
  google_fonts:
  google_maps_flutter:
  geolocator:
  permission_handler:
  flutter_pw_validator:
  intl_phone_field:
  image_picker:
  url_launcher:
  liquid_pull_to_refresh:
  shared_preferences:
  font_awesome_flutter:
  lottie:
  get:
  intl:
  flutter_layout_grid:
  dotted_border:
  shimmer:
  readmore:
  flutter_svg:
  flutter_dotenv:
  flutter_carousel_widget:
  flutter_polyline_points:
  autoscale_tabbarview:
  share_plus:
  screenshot:
  path_provider:
  plugin_platform_interface:
  pdf:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2

flutter_native_splash:
  image: assets/images/splash_screen/frame_1.png
  color: "#f9f9f9"
  image_dark: assets/images/splash_screen/frame_1.png
  color_dark: "#000000"

flutter_launcher_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/images/logo/benji_blue_logo_icon.jpg"
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo/
    - assets/images/vendors/
    - assets/images/splash_screen/
    - assets/images/onboarding_screen/
    - assets/images/vendors/
    - assets/icons/
    - assets/images/rider/
    - assets/images/profile/
    - assets/images/products/
    - assets/images/customers/
    - assets/animations/login/
    - assets/animations/signup/
    - assets/animations/payment/
    - assets/animations/no_internet/
    - assets/animations/error/
    - assets/animations/empty/
    - assets/animations/credit_card/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
